
CI_Portal: PortalValue.cpp
	g++ PortalValue.cpp  MultTcpSvr.cpp Parser.cpp CIValue.cpp -Wall -O2 -o CI_Portal -lpthread /home/Lynuc/CNC/CIComm.so  /usr/xeno-x86/lib/libxenomai.so /usr/xeno-x86/lib/libnative.so
	strip -s CI_Portal

