RobotMaster: RobotMaster.cpp
	g++ RobotMaster.cpp RobotCenter.cpp CFGFILE.cpp  Butt.cpp RITools.cpp Kine.cpp RobotCFG.cpp RobotFT.cpp  -Wall -O2 -o RobotMaster RSHM.so -lpthread -lrt /usr/xeno-x86/lib/libnative.so  /usr/xeno-x86/lib/libxenomai.so /home/Lynuc/CNC/CIComm.so
	strip -s RobotMaster
clean: 
	rm *.o RobotMaster
